language: go

sudo: false

matrix:
  include:
    - go: 1.x
      env:
        - RELEASE=true
        - GO111MODULE=on
    - go: master
      env:
        - RELEASE=false
        - GO111MODULE=on
  allow_failures:
    - go: master

after_success:
  - go build -ldflags="-s -w"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: TfFitvK/e+eBpa9w80DLR7BqOZm90G6xkk7sySMJFnCVX0nMQPyb2mQRADCL7vjk/SISKXCnheMN4GME5C3gQxoyvKEsmQWeE19E1hoOa+e7UyW4rDKEzC17KvYT+k0PYJAfHuRWkzn1m7bPfEgi4o8iMIlK2WeSl804WHrHzLBnrbBwJJ4MNs7CEMWbT15BgX/1IG/bqsJo+V9GI6s8CiWbtkVjCnHw+Kya5ftu6SG4k4AoxdRvfGuUGlbTNRzFd7Ap7mSnzq4L3Sq7K4vnamuILLfyXmLrzT7mV8HaxM3ELC5BvXfrtzDFy/Il8oe6rAfutqmqwM9VgkN1tCD6TMvypgpusv0acwckSuvFxb/0hFb01WRiPAbVtZkfMz4kWGoXChp7UFcr2S+BFdLX0xI6wpN94Xt7MtX+ukt8Quh6LEX989Ls4Bpjcsrwhi7BO9qIpL1QDgKFJ+gh4BGxNx+RhFrXpgqT5F8DZa82Kmcni1o3qq7IiJbHKySRGTvspb/8fnZcllogyJpFNwGwDMcTPPY7Ce4MI2MoghIjXG2D9asiYA2bbj4pHcrWgbxEju1aiGz12CfNTMtU6xkYaQRP/7nbRVZkwDDpWfiJRqCpsnOEKTD62AFARrmz38f9xJXSITcSE7DfMeASdRn/7A4FO021U4sow+8y+eeJ8nE=
  file: go-getmail
  on:
    tags: true
    repo: mback2k/go-getmail
    condition: $RELEASE = true
